# **SERIES**

# **Creating Series**
>There are multiple ways to create a pandas Series:

In [2]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import numpy as np
import pandas as pd

In [4]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array(my_list)
d = {'a':10,'b':20,'c':30}

In [5]:
pd.Series(data = my_list)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series(data = my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [7]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

# **DATA FRAMES**

In [9]:
import numpy as np
import pandas as pd

# **Create a dataframe**
> we can create dataframe from dictionary and list

In [10]:
data = {
    'Name':['Jai', 'Prince', 'Gaurav', 'Anuj'],
    'Age':[27, 24, 22, 32],
    'City':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
    'Salary':[65000,70000,62000,85000]
}
df =pd.DataFrame(data)
df

     Name  Age       City  Salary
0     Jai   27      Delhi   65000
1  Prince   24     Kanpur   70000
2  Gaurav   22  Allahabad   62000
3    Anuj   32    Kannauj   85000

In [11]:
data_list =[
    ['Jai',	27	,'Delhi',	65000],
    ['Prince'	,24,	'Kanpur',	70000],
    ['Gaurav'	,22,	'Allahabad',	62000],
    ['Anuj',	32,	'Kannauj',	85000]

]
df2 = pd.DataFrame(data_list,columns =['Name','Age','City','Salary'])
df2

     Name  Age       City  Salary
0     Jai   27      Delhi   65000
1  Prince   24     Kanpur   70000
2  Gaurav   22  Allahabad   62000
3    Anuj   32    Kannauj   85000

## **Selection and indexing of columns**

In [12]:
df2[['Name','City']]

     Name       City
0     Jai      Delhi
1  Prince     Kanpur
2  Gaurav  Allahabad
3    Anuj    Kannauj

## **Creating a new column**

In [13]:
df2['Designation'] = ['Doctor','Engg','Doctor','Engg']
df2

     Name  Age       City  Salary Designation
0     Jai   27      Delhi   65000      Doctor
1  Prince   24     Kanpur   70000        Engg
2  Gaurav   22  Allahabad   62000      Doctor
3    Anuj   32    Kannauj   85000        Engg

## **Removing Column**

>### only a copy/ snapshot of data no permanent changes in main data

### `Axis = 1 for column & 0 for row`

In [14]:
df2.drop('Designation',axis=1)

     Name  Age       City  Salary
0     Jai   27      Delhi   65000
1  Prince   24     Kanpur   70000
2  Gaurav   22  Allahabad   62000
3    Anuj   32    Kannauj   85000

In [15]:
df2

     Name  Age       City  Salary Designation
0     Jai   27      Delhi   65000      Doctor
1  Prince   24     Kanpur   70000        Engg
2  Gaurav   22  Allahabad   62000      Doctor
3    Anuj   32    Kannauj   85000        Engg

>### To make changes parmament we use
>### inplace keyword

df2.drop('Designation',axis=1,inplace= True)
df2

df2.drop(['Designation','Age'],axis=1,inplace= True)
df2

# **Selecting Rows**

In [16]:
df2.loc[[0,1]]

     Name  Age    City  Salary Designation
0     Jai   27   Delhi   65000      Doctor
1  Prince   24  Kanpur   70000        Engg

> ### iloc - indexed location

In [17]:
df2.iloc[[3,1]]

     Name  Age     City  Salary Designation
3    Anuj   32  Kannauj   85000        Engg
1  Prince   24   Kanpur   70000        Engg

#**Selecting Subsets od Rows and Columns**

In [18]:
df.loc[[0,1]][['City','Salary']]

     City  Salary
0   Delhi   65000
1  Kanpur   70000

In [19]:
df.loc[[2,3]][['Name','Age']]

     Name  Age
2  Gaurav   22
3    Anuj   32

# **Conditional Selection**

In [20]:
df2

     Name  Age       City  Salary Designation
0     Jai   27      Delhi   65000      Doctor
1  Prince   24     Kanpur   70000        Engg
2  Gaurav   22  Allahabad   62000      Doctor
3    Anuj   32    Kannauj   85000        Engg

In [21]:
df2[df2['Age'] > 30]

   Name  Age     City  Salary Designation
3  Anuj   32  Kannauj   85000        Engg

In [22]:
df[(df['Age'] >30) & (df['City'] == "Kannauj")]

   Name  Age     City  Salary
3  Anuj   32  Kannauj   85000

# **Missing data**

In [23]:
data = {
    'A' : [1,2,np.nan,4,5],
    'B' : [5,np.nan,np.nan,3,4],
    'C' : [1,2,3,np.nan,np.nan],
    'D' : [1,np.nan,np.nan,4,5]
}
df = pd.DataFrame(data)
df

     A    B    C    D
0  1.0  5.0  1.0  1.0
1  2.0  NaN  2.0  NaN
2  NaN  NaN  3.0  NaN
3  4.0  3.0  NaN  4.0
4  5.0  4.0  NaN  5.0

In [24]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False   True  False   True
2   True   True  False   True
3  False  False   True  False
4  False  False   True  False

In [25]:
df.isna().sum()

A    1
B    2
C    2
D    2
dtype: int64

> isna().any() -> konsi row m null value h

In [26]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

# **Removing Missing Data**
>` works on row bases`

In [27]:
df

     A    B    C    D
0  1.0  5.0  1.0  1.0
1  2.0  NaN  2.0  NaN
2  NaN  NaN  3.0  NaN
3  4.0  3.0  NaN  4.0
4  5.0  4.0  NaN  5.0

### **deleting rows containing null value**

In [28]:
df.dropna()

     A    B    C    D
0  1.0  5.0  1.0  1.0

> `thresh --> at =least 3 non null vaues `

In [29]:
df.dropna(thresh=3)

     A    B    C    D
0  1.0  5.0  1.0  1.0
3  4.0  3.0  NaN  4.0
4  5.0  4.0  NaN  5.0

In [30]:
df.fillna(0 )

     A    B    C    D
0  1.0  5.0  1.0  1.0
1  2.0  0.0  2.0  0.0
2  0.0  0.0  3.0  0.0
3  4.0  3.0  0.0  4.0
4  5.0  4.0  0.0  5.0

In [31]:
df.fillna(df.mean())

     A    B    C         D
0  1.0  5.0  1.0  1.000000
1  2.0  4.0  2.0  3.333333
2  3.0  4.0  3.0  3.333333
3  4.0  3.0  2.0  4.000000
4  5.0  4.0  2.0  5.000000

# **Merging 2 dataframes**

In [32]:
employees = pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'Name':['John','Anna','Raj','Linda','Bob'],
    'Department':['Accounting','IT','IT','HR','Accounting']
})

Salaries = pd.DataFrame({
    'employee_id': [1,2,3,6,7],
    'salaries' : [60000,80000,65000,70000,90000],
    'bonus' : [5000,10000,7000,8000,12000]
})
employees

   employee_id   Name  Department
0            1   John  Accounting
1            2   Anna          IT
2            3    Raj          IT
3            4  Linda          HR
4            5    Bob  Accounting

In [33]:
Salaries

   employee_id  salaries  bonus
0            1     60000   5000
1            2     80000  10000
2            3     65000   7000
3            6     70000   8000
4            7     90000  12000

In [34]:
pd.merge(employees, Salaries)

   employee_id  Name  Department  salaries  bonus
0            1  John  Accounting     60000   5000
1            2  Anna          IT     80000  10000
2            3   Raj          IT     65000   7000

In [35]:
pd.merge(employees, Salaries,on = "employee_id",how= 'inner')

   employee_id  Name  Department  salaries  bonus
0            1  John  Accounting     60000   5000
1            2  Anna          IT     80000  10000
2            3   Raj          IT     65000   7000

In [36]:
pd.merge(employees, Salaries,on = "employee_id",how= 'outer')

   employee_id   Name  Department  salaries    bonus
0            1   John  Accounting   60000.0   5000.0
1            2   Anna          IT   80000.0  10000.0
2            3    Raj          IT   65000.0   7000.0
3            4  Linda          HR       NaN      NaN
4            5    Bob  Accounting       NaN      NaN
5            6    NaN         NaN   70000.0   8000.0
6            7    NaN         NaN   90000.0  12000.0

In [37]:
# based on employee
pd.merge(employees, Salaries,on = "employee_id",how= 'left')

   employee_id   Name  Department  salaries    bonus
0            1   John  Accounting   60000.0   5000.0
1            2   Anna          IT   80000.0  10000.0
2            3    Raj          IT   65000.0   7000.0
3            4  Linda          HR       NaN      NaN
4            5    Bob  Accounting       NaN      NaN

In [38]:
# based on Salary
pd.merge(employees, Salaries,on = "employee_id",how= 'right')

   employee_id  Name  Department  salaries  bonus
0            1  John  Accounting     60000   5000
1            2  Anna          IT     80000  10000
2            3   Raj          IT     65000   7000
3            6   NaN         NaN     70000   8000
4            7   NaN         NaN     90000  12000

# **Concatination of 2 dataframe**

In [39]:
df1 = pd.DataFrame({
    'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3'],
    'C':['C0','C1','C2','C3']
})

df2 = pd.DataFrame({
    'A':['A4','A5','A6','A7'],
    'B':['B4','B5','B6','B7'],
    'C':['C4','C5','C6','C7']
})
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

In [40]:
df2

    A   B   C
0  A4  B4  C4
1  A5  B5  C5
2  A6  B6  C6
3  A7  B7  C7

In [41]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
0  A4  B4  C4
1  A5  B5  C5
2  A6  B6  C6
3  A7  B7  C7

In [42]:
pd.concat([df1,df2],axis= 1)

    A   B   C   A   B   C
0  A0  B0  C0  A4  B4  C4
1  A1  B1  C1  A5  B5  C5
2  A2  B2  C2  A6  B6  C6
3  A3  B3  C3  A7  B7  C7

# **Joining of 2 DataFrame**

In [43]:
df1 = pd.DataFrame({
    'name' : ['ALice','Bob','Charlie']
},index =[1,2,3])

df2 = pd.DataFrame({
    'Score' : [70,80,90]
},index = [2,3,4])
df1

      name
1    ALice
2      Bob
3  Charlie

In [44]:
df2

   Score
2     70
3     80
4     90

In [45]:
df1.join(df2)

      name  Score
1    ALice    NaN
2      Bob   70.0
3  Charlie   80.0

In [46]:
df1.join(df2,how = 'outer')

      name  Score
1    ALice    NaN
2      Bob   70.0
3  Charlie   80.0
4      NaN   90.0

# **GroupBy** - on categorical data
> it creates an object that we can't see

In [47]:
data = {
    'Category' : ['A','B','A','B','A','B','A','B'],
    'Store' : ['S1','S1','S2','S2','S1','S2','S2','S1'],
    'Sales' : [100,200,150,300,250,350,200,300],
    'Quantity' : [10,15,12,18,8,20,15,15],
    'Date' : pd.date_range('2023-01-01',periods=8)}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    300        18 2023-01-04
4        A    S1    250         8 2023-01-05
5        B    S2    350        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        15 2023-01-08

> Q- Group by Category and Calculate  the sum of Sales

In [48]:
df.groupby('Category')['Sales'].sum()

Category
A     700
B    1150
Name: Sales, dtype: int64

In [49]:
cat = df.groupby('Category')
cat.get_group('A')

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    250         8 2023-01-05
6        A    S2    200        15 2023-01-07

In [50]:
cat = df.groupby('Category')
cat
for i,v in cat:
  print(i)
  print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    250         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    300        18 2023-01-04
5        B    S2    350        20 2023-01-06
7        B    S1    300        15 2023-01-08

> Q - Group by Store and calculate the sum of sales

In [51]:
df.groupby('Store')['Sales'].sum()

Store
S1     850
S2    1000
Name: Sales, dtype: int64

> Q- Group multiple columns

> Q- group by Category and store

In [52]:
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       350
          S2       350
B         S1       500
          S2       650
Name: Sales, dtype: int64

# **Aggregation**

> basic agg func -->

*   Mean
*   Median
*   Mode

In [53]:
df['Sales'].mean()

np.float64(231.25)

In [54]:
df['Sales'].median()

225.0

In [55]:
df['Sales'].mode()

0    200
1    300
Name: Sales, dtype: int64

In [56]:
df['Sales'].min()

100

In [57]:
df['Sales'].max()

350

In [58]:
df['Sales'].count()

np.int64(8)

In [59]:
df['Sales'].std()

84.25090080061035

In [60]:
df['Sales'].agg(['sum','mean','median','min','max','std'])

sum       1850.000000
mean       231.250000
median     225.000000
min        100.000000
max        350.000000
std         84.250901
Name: Sales, dtype: float64

# **Pivot Tables**
> we use ***agg func***

In [61]:
import numpy as np
import pandas as pd

In [62]:
data = {
    'dates': pd.date_range('2023-01-01', periods=20),
    'product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Webcam'] * 4,
    'region': ['North', 'South', 'East','West'] * 5,
    'sales': np.random.randint(100, 1000, 20),
    'units': np.random.randint(1, 10, 20),
    'rep': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'] * 4
}
df_new = pd.DataFrame(data)

df_new['Month'] = df_new['dates'].dt.month_name()
df_new['Quarter'] = 'Q' + df_new['dates'].dt.quarter.astype(str)
df_new

        dates   product region  sales  units      rep    Month Quarter
0  2023-01-01    Laptop  North    828      8    Alice  January      Q1
1  2023-01-02     Mouse  South    901      3      Bob  January      Q1
2  2023-01-03  Keyboard   East    299      8  Charlie  January      Q1
3  2023-01-04   Monitor   West    673      3    David  January      Q1
4  2023-01-05    Webcam  North    292      6      Eve  January      Q1
5  2023-01-06    Laptop  South    151      1    Alice  January      Q1
6  2023-01-07     Mouse   East    586      3      Bob  January      Q1
7  2023-01-08  Keyboard   West    935      9  Charlie  January      Q1
8  2023-01-09   Monitor  North    547      4    David  January      Q1
9  2023-01-10    Webcam  South    795      3      Eve  January      Q1
10 2023-01-11    Laptop   East    442      3    Alice  January      Q1
11 2023-01-12     Mouse   West    417      9      Bob  January      Q1
12 2023-01-13  Keyboard  North    955      3  Charlie  January      Q1
13 2023-01-14   Monitor  South    542      5    David  January      Q1
14 2023-01-15    Webcam   East    421      1      Eve  January      Q1
15 2023-01-16    Laptop   West    517      6    Alice  January      Q1
16 2023-01-17     Mouse  North    153      7      Bob  January      Q1
17 2023-01-18  Keyboard  South    518      3  Charlie  January      Q1
18 2023-01-19   Monitor   East    584      8    David  January      Q1
19 2023-01-20    Webcam   West    118      7      Eve  January      Q1

In [63]:
pd.pivot_table(df_new,values ='sales',index = 'region',columns = 'product')

product  Keyboard  Laptop  Monitor  Mouse  Webcam
region
East        299.0   442.0    584.0  586.0   421.0
North       955.0   828.0    547.0  153.0   292.0
South       518.0   151.0    542.0  901.0   795.0
West        935.0   517.0    673.0  417.0   118.0

In [64]:
pd.pivot_table(df_new,values =['sales','units'],index = 'region',columns = 'product')

           sales                                 units                       \
product Keyboard Laptop Monitor  Mouse Webcam Keyboard Laptop Monitor Mouse
region
East       299.0  442.0   584.0  586.0  421.0      8.0    3.0     8.0   3.0
North      955.0  828.0   547.0  153.0  292.0      3.0    8.0     4.0   7.0
South      518.0  151.0   542.0  901.0  795.0      3.0    1.0     5.0   3.0
West       935.0  517.0   673.0  417.0  118.0      9.0    6.0     3.0   9.0


product Webcam
region
East       1.0
North      6.0
South      3.0
West       7.0

# **Cross Tabs**
> we use ***counting func***

In [65]:
pd.crosstab(df_new['region'],df_new['product'])

product  Keyboard  Laptop  Monitor  Mouse  Webcam
region
East            1       1        1      1       1
North           1       1        1      1       1
South           1       1        1      1       1
West            1       1        1      1       1

#**DataFrame operations**

In [66]:
df1 = pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C':[100,200,300,400,500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [67]:
df1.shape

(5, 3)

In [68]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [69]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [70]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [71]:
# changes in column data by broadcast
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

# **Dataframe Applying Function**

In [72]:
def square(x):
  return x**2
square(df1)

    A     B       C
0   1   100   10000
1   4   400   40000
2   9   900   90000
3  16  1600  160000
4  25  2500  250000

In [73]:
df1['B'] = df1['B'].apply(square)

In [74]:
df1

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500

In [75]:
df1['D'] = df1['B'].apply(square)

In [76]:
df1

   A     B    C        D
0  1   100  100    10000
1  2   400  200   160000
2  3   900  300   810000
3  4  1600  400  2560000
4  5  2500  500  6250000

In [78]:
df1['D'] = df1['B'].apply(lambda x : x**2)
df1

   A     B    C        D
0  1   100  100    10000
1  2   400  200   160000
2  3   900  300   810000
3  4  1600  400  2560000
4  5  2500  500  6250000